Queued jobs documentation improvements
silverstripe-australia/silverstripe-queuedjobs pull request #281
Opened 2020-02-17 22:50 UTC by mfendeksilverstripe

# Documentation update

*

2020-02-19 05:14 UTC, maxime-rainville requested changes
Epic effort Mojmir!!! You're doing God's work.

I left a bunch of stylistic suggestion. I'm not the most familiar with the queued job module, so I'm probably not the best person to judge whether what you wrote make any sense.

Just hit me up if you have any questions.

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +One of the advantages of file locking is that in case of emergency when the site crashes and CMS is not available, you may still be able to get access to the filesystem and change the file lock manua
```suggestion
One benefit of file locking is that in case of critical failure (e.g.: the site crashes and CMS is not available), you may still be able to get access to the filesystem and change the file lock manually.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +This guide is recommended for developers who are already familiar with basic concepts and want to take full advantage of the features in this module.
```suggestion
This section is recommended for developers who are already familiar with basic concepts and want to take full advantage of the features in this module.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* you create a job instance in your code and queue it (this is a constructor call with params)
What's this list about? Are those pre-condition that need to be met before proceeding? Are those scenarios where this would be helpful?

Please clarify.

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* you create a job instance in your code and queue it (this is a constructor call with params)
If these two entries are meant to match Option 1 and Option 2 below, please make this explicit.

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +```
```suggestion
```php
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +`Job class`
Maybe add a sentence or two explaining what this option is before end.

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +`Job class`
```suggestion
##### Job class
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +`Job creation`
```suggestion
##### Job creation
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +```
```suggestion
```php
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +This approach is especially problematic on PHP 7.3 or higher as there the static syntax checker may have an issue with nullable values and force you to implement additional check like `is_countable`
```suggestion
This approach is especially problematic on PHP 7.3 or higher as the static syntax checker may have an issue with nullable values and force you to implement additional check like `is_countable` on the job properties.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* nullable values need to be provided and code handling of the nullable values has to be present (because the queue runner calls the constructor without params as data will come in later from job des
```suggestion
* Nullable values need to be provided and code handling of the nullable values has to be present. That is necessary because the queue runner calls the constructor without parameters as data will come in later from job descriptor.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* strict type is not completely strict because nullable values can be passed when they shouldn't be (job creation in your code)
```suggestion
* Strict type is not completely strict because nullable values can be passed when they shouldn't be (e.g.: at job creation in your code).
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +
Add a sentence or two here

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +`Job class`
```suggestion
##### Job class
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +```
```suggestion
```php
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +`Job creation`
```suggestion
##### Job creation
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +```
```suggestion
```php
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* nullable values don't need to be handled
```suggestion
* Nullable values don't need to be handled.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* no strict param types
```suggestion
* No strict parameter types.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +This approach is probably the simpliest one but with least param validation.
```suggestion
This approach is probably the simplest one but with least parameter validation.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +
Add a blurb.

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +`Job class`
```suggestion
##### Job class
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +```
```suggestion
```php
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +`Job creation`
```suggestion
##### Job creation
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +```
```suggestion
```php
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +`Unit tests`
```suggestion
##### Unit tests
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +```
```suggestion
```php
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +other assertions can be placed here (job side effects, job data assertions...)
```suggestion
// other assertions can be placed here (job side effects, job data assertions...)
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* strict param type checking
```suggestion
* Strict parameter type checking.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* no nullable values
```suggestion
* No nullable values.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* no issues with PHP 7.3 or higher
```suggestion
* No issues with PHP 7.3 or higher.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* typed params
```suggestion
* Typed parameters.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* separate method has to be implemented and called after job creation in your code
```suggestion
* Separate method has to be implemented and called after job creation in your code.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +This option is recommended for project setup which havs many job types with complex processing as strict checking reduces the risk of input error.
```suggestion
This option is recommended for project which have many job types with complex processing as strict checking reduces the risk of input error.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +There is no precise answer as this really depends on your project setup but there are some good practices that should be considered.
```suggestion
There is no precise answer. This really depends on your project setup but there are some good practices that should be considered:
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* `similar size` - the more narrow is the range of job sizes the easier is to optimise the queue settings and stack size to suit your project
```suggestion
* similar size — the more narrow is the range of job sizes the easier is to optimise the queue settings and stack size to suit your project
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* `split the job work into steps` - this prevents your job to be running too long without an update to the job manager and lowers the risk of the job getting labeled as crashed
```suggestion
* split the job work into steps — this prevents your job to be running too long without an update to the job manager and lowers the risk of the job getting labelled as crashed
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* `avoid jobs that are too small` - jobs that are too small produce a large amount of job management overhead and are thus ineffective
```suggestion
* avoid jobs that are too small — jobs that are too small produce a large amount of job management overhead and are thus inefficient
```
I think "inefficient" (not achieving maximum productivity) is a better word here than "ineffective" (not producing any significant or desired effect).

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* `avoid jobs that are too large` - jobs that are too large are difficult to execute as they may cause timeout issues during execution
```suggestion
* avoid jobs that are too large — jobs that are too large are difficult to execute as they may cause timeout issues during execution.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +As a general rule of thumb one run of `process()` method in your job should not take more than `30 seconds`.
```suggestion
As a general rule of thumb, one run of `process()` method in your job should not take more than 30 seconds.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* add job steps or review job steps if already present
```suggestion
* add job steps or review job steps if already present
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* split the job into several smaller, dependant jobs
```suggestion
* split the job into several smaller dependant jobs.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +General recommendations are
```suggestion
You should also consider these general recommendations:
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* `majority case` use Job steps approach for work that represents one whole that should be completed as in one go and has little value when only partially completed
```suggestion
* "majority case" use Job steps approach for work that represents one whole that should be completed in one go and has little value when only partially completed,
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* `minority case` use Dependant jobs approach for work that represents multiple parts that can be completed independently, i.e. there is value of only one part being completed
```suggestion
* "minority case" use dependant jobs approach for work that represents multiple parts that can be completed independently, i.e. there is value even if only one part is completed
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* `majority case` use Job steps approach for work that represents one whole that should be completed as in one go and has little value when only partially completed
Are you trying to say that the majority of your jobs should be covered by the first point and that the second point should only cover a minority of jobs. It's not clear to me.

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +Note that even if you go with dependant jobs approach, you should still implement steps for the individual jobs if it makes sense.
```suggestion
Note that even if you choose the dependant jobs approach, you should still implement steps for the individual jobs if it makes sense.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +For example a static cache job should process each URL as a separate step even though there is a follow up job which handles CDN flush for the URLs.
```suggestion
For example, a static cache job should process each URL as a separate step even though there is a follow up job which handles CDN flush for the URLs.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +Dependant jobs approach also allows you to run these jobs in parallel on some project setups.
```suggestion
The dependant job approach also allows you to run these jobs in parallel on some project setups.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +Job steps on the other hand always run in sequence.
```suggestion
Job steps, on the other hand, always run in sequence.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* indicate progress to the job manager so it could know if the job execution is still underway
```suggestion
* Communicating progress to the job manager so it can know if the job execution is still underway.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +Job step feature has two main functions:
```suggestion
The job step feature has two main purposes.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* provide a checkpoint in case job execution is interrupted for some reason, this will allow the job to resume from the last step processed instead of restarting the job from the beginning
```suggestion
* Providing a checkpoint in case job execution is interrupted for some reason. This allows the job to resume from the last step completed instead of restarting from the beginning.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +Current job step can also be observed in the CMS via the Jobs admin UI. This is useful mostly for debugging purposes when monitoring job execution.
```suggestion
Current job step can also be observed in the CMS via the _Jobs admin_ UI. This is useful mostly for debugging purposes when monitoring job execution.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +Job step `should not` be used to determine if job is complete or not. You should rely on the job data or database state instead.
```suggestion
Job step *should not* be used to determine if a job is completed or not. You should rely on the job data or database state instead.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +For example consider a job which accept a list of items to process and each item represents a separate step.
```suggestion
For example, consider a job which accept a list of items to process and each item represents a separate step.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +```
```suggestion
```php
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> + * @package App\Jobs
```suggestion
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +This job setup has following features
```suggestion
This job setup has following features:
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* original list of items is preserved in the job data so it can be used for other purposes (dependant jobs, debug...)
```suggestion
* original list of items is preserved in the job data so it can be used for other purposes (dependant jobs, debug).
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +For example consider following flow:
```suggestion
For example, consider the following flow:
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* page flushes cache on CDN for provided URLs
```suggestion
* page flushes cache on CDN for provided URLs.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +Note that these actions have to be done is sequence so we may not be able to queue all needed jobs right away.
```suggestion
Note that these actions have to be done in sequence, so we may not be able to queue all needed jobs right away.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +* later actions have data dependencies on earlier actions
```suggestion
* later actions have data dependencies on earlier actions.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +In this situation it's recommended to use the `Dependant job` approach.
```suggestion
In this situation, it's recommended to use the _Dependant job_ approach.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +```
```suggestion
```php
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +Use the `updateJobDescriptorAndJobOnCompletion` extension point in `QueuedJobService::runJob()` like this
```suggestion
Use the `updateJobDescriptorAndJobOnCompletion` extension point in `QueuedJobService::runJob()` like this:
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +You have the access to job object and job descriptor in the extension point so if you need any data from previous job simply use these two variables to access the needed data.
```suggestion
You have the access to the job object and to the job descriptor in the extension point. If you need any data from the previous job, simply use these two variables to access the needed data.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +Going back to our example we would use the extension point to look for static cache job, i.e. if the completed job is not static cache job, just exit early.
```suggestion
Going back to our example, we would use the extension point to look for the static cache job, i.e. if the completed job is not the static cache job, just exit early.
```

2020-02-19 05:14 UTC, maxime-rainville commented on README.md
> +As a consequence, the work that we want get done may end up being very fragmented and each chunk may be processed at a different time.
```suggestion
As a consequence, the work might end up being very fragmented and each chunk may be processed at a different time.
```

2020-02-19 05:14 UTC, maxime-rainville requested changes
Epic effort Mojmir!!! You're doing God's work.

I left a bunch of stylistic suggestion. I'm not the most familiar with the queued job module, so I'm probably not the best person to judge whether what you wrote make any sense.

Just hit me up if you have any questions.

2020-02-19 18:25 UTC, mfendeksilverstripe commented on README.md
> +* `majority case` use Job steps approach for work that represents one whole that should be completed as in one go and has little value when only partially completed
yes, that's correct. Will try to improve the description

2020-02-19 19:24 UTC, mfendeksilverstripe commented on README.md
> +* add job steps or review job steps if already present
What is this?

2020-02-19 19:34 UTC, mfendeksilverstripe commented
@maxime-rainville Thanks for the feedback, it's greatly appreciated. I pushed up some fixes, please have another look.

2020-03-05 23:30 UTC, maxime-rainville requested changes
Big improvement. That's much clearer. I made some more minor grammatical suggestions.

But otherwise, it's almost ready to go.

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +3. job is picked and processed up by the queue runner
```suggestion
3. job is picked and processed up by the queue runner.
```

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +##### Job class
Maybe rename the "Job class" headers to "job class constructor". Otherwise this one looks a bit weird.

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +The implementation needs to provide default values for all params and handle this special case.
```suggestion
The implementation needs to provide default values for all parameters and handle this special case.
```

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +The inherited constructor has a generic params array as the only input and we can use it to pass arbitrary params to our job.
```suggestion
The inherited constructor has a generic parameter array as the only input and we can use it to pass arbitrary parameters to our job.
```

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +This approach is probably the simplest one but with least parameter validation.
```suggestion
This approach is probably the simplest one but with the least parameter validation.
```

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +This approach is the most strict when it comes to validating params but requires the `hydrate` method to be called after each job creation.
```suggestion
This approach is the strictest when it comes to validating parameters but requires the `hydrate` method to be called after each job creation.
```

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +This option is recommended for projects which have many job types with complex processing as strict checking reduces the risk of input error.
```suggestion
This option is recommended for projects which have many job types with complex processing. Strict checking reduces the risk of input error.
```

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +* similar size — the more narrow is the range of job sizes the easier is to optimise the queue settings and stack size to suit your project
```suggestion
* similar size — it's easier to optimise the queue settings and stack size of your project when your jobs are about the same size
```

I think that says about the same thing, but is a little easier to understand.

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +* split the job work into steps — this prevents your job to be running too long without an update to the job manager and lowers the risk of the job getting labelled as crashed
```suggestion
* split the job work into steps — this prevents your job running for too long without an update to the job manager and it lowers the risk of the job getting labelled as crashed
```

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +As a general rule of thumb, one run of `process()` method in your job should not take more than 30 seconds.
```suggestion
As a general rule of thumb, one run of your job's `process()` method should not exceed 30 seconds.
```

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +* in case you already use steps you may want to review how large the steps are, maybe they can be made smaller
```suggestion
* If you're job is already divided in steps, try dividing the larger steps into smaller ones.
```

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +* split the job into several smaller dependant jobs for work that represents multiple parts that can be completed independently, i.e. there is value even if only one part is completed
```suggestion
* If your job performs actions that can be completed independently from the others, you can split the job into several smaller dependant jobs (e.g.: there is value even if only one part is completed).
```

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +* add job steps which help the job manager to determine if job is still being processed
```suggestion
* Add job steps which help the job manager to determine if job is still being processed.
```

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +The dependant job approach also allows you to run these jobs in parallel on some project setups.
```suggestion
The dependant job approach also allows you to run these jobs concurrently on some project setups.
```

I think "concurrently" is more precise in this context.

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +Correct implementation of jobs steps makes your jobs more robust, resilient and reliable.
"robust, resilient and reliable"

Those 3 adjectives more or less all mean the same thing.

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +* Communicating progress to the job manager so it can know if the job execution is still underway.
```suggestion
* Communicating progress to the job manager so it knows if the job execution is still underway.
```

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +* Providing a checkpoint in case job execution is interrupted for some reason. This allows the job to resume from the last step completed instead of restarting from the beginning.
```suggestion
* Providing a checkpoint in case job execution is interrupted for some reason. This allows the job to resume from the last completed step instead of restarting from the beginning.
```

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +Current job step can also be observed in the CMS via the _Jobs admin_ UI. This is useful mostly for debugging purposes when monitoring job execution.
```suggestion
The currently executing job step can also be observed in the CMS via the _Jobs admin_ UI. This is useful mostly for debugging purposes when monitoring job execution.
```

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +Job step *should not* be used to determine if a job is completed or not. You should rely on the job data or database state instead.
```suggestion
Job steps *should not* be used to determine if a job is completed or not. You should rely on the job data or the database state instead.
```

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +
```suggestion
```

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +public function updateJobDescriptorAndJobOnCompletion(QueuedJobDescriptor $descriptor, QueuedJob $job): void
```suggestion
public function updateJobDescriptorAndJobOnCompletion(
    QueuedJobDescriptor $descriptor, 
    QueuedJob $job
): void
```

2020-03-05 23:30 UTC, maxime-rainville commented on README.md
> +You have the access to the job object and to the job descriptor in the extension point. If you need any data from the previous job, simply use these two variables to access the needed data.
```suggestion
You have access to the job object and to the job descriptor in the extension point. If you need any data from the previous job, simply use these two variables to access the needed data.
```

2020-03-12 22:32 UTC, mfendeksilverstripe commented
@maxime-rainville Pushed PR fixes and a job status flowchart

2020-05-01 05:50 UTC, maxime-rainville approved these changes
Looks good.

2020-05-01 05:50 UTC, merged