NEW: Better Descriptor edit form UI.
silverstripe-australia/silverstripe-queuedjobs pull request #314
Opened 2020-06-15 01:51 UTC by mfendeksilverstripe

# Better Descriptor edit form UI

UI improvements for Queued Job Descriptor edit form.

## Problem

* Descriptor UI uses mostly scaffolded fields which very little description information
* using individual fields for the intended purpose is really difficult and confusing
* editing data through this form often requires extensive reading of documentation and source code

## Solution

* more descriptive UI with better naming convention
* additional context information where needed

## Preview

![main](https://user-images.githubusercontent.com/26395487/84610624-5134b380-af0f-11ea-89d5-fcd903fa2a72.png)

![advanced](https://user-images.githubusercontent.com/26395487/84610631-57c32b00-af0f-11ea-9548-e751e87de801.png)

## Related issues

https://github.com/symbiote/silverstripe-queuedjobs/issues/260

2020-08-26 22:23 UTC, emteknetnz requested changes
Looks great, some minor text changes

2020-08-26 22:23 UTC, emteknetnz commented on src/DataObjects/QueuedJobDescriptor.php
> +            . ' exactly at the specified time (it can start later).'
```suggestion
            . ' exactly at the specified time (it will start the next time the cron job runs).'
```

2020-08-26 22:23 UTC, emteknetnz commented on src/DataObjects/QueuedJobDescriptor.php
> +                'Number of times this job stalled and was resumed (limit %d).',
```suggestion
                'Number of times this job stalled and was resumed (limit of %d time(s)).',
```

2020-08-26 22:23 UTC, emteknetnz commented on src/DataObjects/QueuedJobDescriptor.php
> +            'Fill this out if you want to prevent the job from starting earlier than the specified time.'
```suggestion
            'Used to prevent the job from starting earlier than the specified time.'
```

2020-08-26 22:23 UTC, emteknetnz commented on src/DataObjects/QueuedJobDescriptor.php
> +                'Select a user you want to be used to run this job.'
```suggestion
                'Select a user to be used to run this job.'
```

2020-08-31 00:42 UTC, mfendeksilverstripe commented
@emteknetnz Thanks for great suggestions, updated the PR, please review.

2020-09-01 01:36 UTC, merged