BUG: Allow zero values for integers and floats within queued job rule.
silverstripe-australia/silverstripe-queuedjobs pull request #337
Opened 2021-03-01 20:16 UTC by mfendeksilverstripe

# Allow zero values for integers and floats within queued job rule

Zero values for integers and floats within queued job rule are needed to cover the cases where high memory or processor use should prevent any new jobs from being started. This is currently impossible to set even though it's internally supported within the `AsyncPHP\Doorman\Rules\InMemoryRules::canRunTask`.

This change-set allows zero values to be set for integers and floats.

2021-03-08 04:09 UTC, maxime-rainville reviewed
Just clarifying the problem to make sure I understand. So you need to be able to set these values to `0`, but because all those getters return their default value when ever a "falsy" value is provided, your ZEROs are always ignored.

How would you actually use this in practice? You would create a Rule for a job and set the process to zero to block any other job from running while that job is running?

2021-03-08 18:38 UTC, mfendeksilverstripe commented
That's correct @maxime-rainville , here is some more information as requested:

![Screen Shot 2021-03-09 at 7 26 21 AM](https://user-images.githubusercontent.com/26395487/110365155-8ee2f900-80a9-11eb-9a79-881fbc93bd10.png)

In the example above we have a rule saying that if your memory usage is between 75 and 100 you should create only one new process but what we actually want to do is to set it to 0 - if memory usage is between 75 and 100 we want to create 0 new processes. Same for processor use.

![Screen Shot 2021-03-09 at 7 29 34 AM](https://user-images.githubusercontent.com/26395487/110365188-999d8e00-80a9-11eb-9a0b-ae11115e992f.png)

Note that you can actually store a 0 on a `QueuedJobRule` model in the DB but when the value is fetched from the DB it's going through that getter and it will override the value.

Note that the [actual execution](https://github.com/asyncphp/doorman/blob/3.1.0/src/Rules/InMemoryRules.php#L59) of the `QueuedJobRule` is implemented in a way to check for nulls not falsy values.

2021-03-08 22:35 UTC, maxime-rainville requested changes
That sound good. I presume that the screen shot you have in your last comment comes from a custom gridfield you implemented because I can't find it anywhere.

Can you add some unit test to cover that those getters handle `0` as you expect them to and return the correct value? 

Probably don't need to add a unit test to cover that providing a 0 ends up having the intended affects on the queues since that's handle by the third party package.

2021-03-08 23:05 UTC, mfendeksilverstripe commented
Yes, that's a custom `GridField`. Sure I'll add unit tests for that.

2021-03-09 19:41 UTC, mfendeksilverstripe commented
@maxime-rainville Added the unit tests as requested. Please review.

2021-03-09 20:45 UTC, maxime-rainville approved these changes
Looks good

2021-03-09 20:45 UTC, merged