Fix error handling exception on initialisation
silverstripe-australia/silverstripe-queuedjobs pull request #348
Opened 2021-06-01 03:03 UTC by matt-in-a-hat

Fixes https://github.com/symbiote/silverstripe-queuedjobs/issues/316
Work around to not change the method signature (so as to not require a major version change).

2022-05-31 08:23 UTC, kinglozzer approved these changes

2022-05-31 08:25 UTC, kinglozzer requested changes

2022-05-31 08:25 UTC, kinglozzer commented on src/Services/QueuedJobService.php
> +                    $job = QueuedJob::singleton();
Oops, my review was premature - `QueuedJob` is an interface, so this won’t work

2023-12-22 01:05 UTC, GuySartorelli commented
The issue this PR links to was closed as fixed by https://github.com/symbiote/silverstripe-queuedjobs/pull/374

2023-12-22 01:05 UTC, closed without merging