Remove stalled job if implementation not found
silverstripe-australia/silverstripe-queuedjobs pull request #350
Opened 2021-07-07 02:01 UTC by wilr

If a job class is renamed or removed, remove the related stalled jobs rather than throwing an exception (which prevents the rest of the jobs from running).

2021-07-08 11:51 UTC, dhensby commented
linting issues :)

2021-07-26 04:26 UTC, wilr commented
@dhensby lint issue fixed

2021-08-05 22:20 UTC, emteknetnz requested changes

2021-08-05 22:20 UTC, emteknetnz commented on src/Jobs/DoormanQueuedJobTask.php
> +    public function getDescriptor(): ?QueuedJobDescriptor
Technically an API change, could you remove this change

2021-08-05 23:21 UTC, emteknetnz approved these changes
Good

2021-08-05 23:22 UTC, merged