NEW: Default jobs / queue type configuration.
silverstripe-australia/silverstripe-queuedjobs pull request #365
Opened 2022-02-02 20:00 UTC by mfendeksilverstripe

# NEW: Default jobs / queue type configuration.

Added a new configuration option to specify queue type for default jobs. This is handy in case multiple queue are used and you want only one of them to run default jobs.

2022-05-18 02:00 UTC, emteknetnz requested changes
Looks good

Could you please add QueuedJobServiceTest.php and add a quick test for this.  Update the config and then assert the `->defaultJobs` array has what's expected

2022-05-19 02:39 UTC, mfendeksilverstripe commented
@emteknetnz I've added a test for this, please review.

2022-06-03 00:19 UTC, emteknetnz requested changes
Have tested locally, it works.  I think we should update the key name used as well as the jobType/queue in the readme example

2022-06-03 00:19 UTC, emteknetnz commented on docs/en/default-jobs.md
> +          queue: 1 # This would make this job be picked up only by Immediate queue
```suggestion
          jobType: 2 # This would make this job be picked up only by the QUEUED queue
```

Rather than use `queue` which matches the variable `$queue`, I think we should using `jobType` key as it matches the interface

**QueuedJob.php**
```php
    /**
     * What type of job is this? Options are
     * - QueuedJob::IMMEDIATE
     * - QueuedJob::QUEUED
     * - QueuedJob::LARGE
     */
    public function getJobType();
```

Also I think we should change the value in the readme from `1` to `2` (and the corresponding comment) because that's the queue that gets run on `vendor/bin/sake dev/tasks/ProcessJobQueueTask`, so it's much easier for user to validate that this is working.

2022-06-14 02:15 UTC, mfendeksilverstripe commented
@emteknetnz I've updated the name as requested, please review.

2022-06-14 21:57 UTC, emteknetnz approved these changes
Tested locally, works as it should

2022-06-14 21:57 UTC, merged