FIX Broken builds
silverstripe-australia/silverstripe-queuedjobs pull request #397
Opened 2023-02-15 03:13 UTC by sabina-talipova

### Description
Draft version of PR. Looks like `InjectionCreator::create` doesn't work as expected. But, probably it's an issue in my local environment.

### Parent issue
- https://github.com/silverstripeltd/product-issues/issues/676

### Broken build
- https://github.com/silverstripe/recipe-kitchen-sink/actions/runs/4121094495/jobs/7116461834

2023-02-15 03:36 UTC, emteknetnz requested changes
Just a note - this PR isn't meant to be merged in its current state

2023-02-15 03:36 UTC, emteknetnz commented on src/Services/QueuedJobService.php
> +        if (!$this->queueHandler) {
We shouldn't be doing this, a hard exception here is better if `$this->queueHandler` is falsey

`$this->queueHandler` is set via Injector as specified in [yml config](https://github.com/symbiote/silverstripe-queuedjobs/blob/4/_config/queuedjobs.yml#L12) - , by default it is [configured](https://github.com/symbiote/silverstripe-queuedjobs/blob/4/_config/queuedjobs.yml#L6) to use DefaultQueueHandler

2023-02-15 03:36 UTC, emteknetnz commented on src/Extensions/ScheduledExecutionExtension.php
> +                $queuedJobService = new QueuedJobService();
We shouldn't be changing `::create()` to `new`

2023-02-15 03:36 UTC, emteknetnz commented on src/Services/QueuedJobService.php
> +                        $this->queueJob($queuedJob, $queuDate);
We shouldn't be doing this - we should be using the singleton which presumbably is being used as the central class to keep a record of all the data

2023-02-15 03:36 UTC, emteknetnz commented on src/Services/QueuedJobService.php
> +                $queuedJobHandler = new QueuedJobHandler($job, $jobDescriptor);
We shouldn't be changing `::create()` to `new`

2023-02-16 00:26 UTC, sabina-talipova commented
Close as irrelevant to fixing issue.

2023-02-16 00:26 UTC, closed without merging