Replace assignment with intended comparison
silverstripe-australia/silverstripe-queuedjobs pull request #421
Opened 2024-04-24 20:04 UTC by oddnoc

## Expected behaviour

If `E_DEPRECATED` is defined and `$errno` is either `E_DEPRECATED` or `E_USER_DEPRECATED`, return from `handleError()`.

## Actual behaviour

If `E_DEPRECATED` is defined and `$errno` is any value, return from `handleError()`. This means that exceptions are never thrown by the method whenever `E_DEPRECATED` is defined.

2024-04-25 21:08 UTC, GuySartorelli requested changes

2024-04-25 21:08 UTC, GuySartorelli commented on src/Services/JobErrorHandler.php
> +                if (E_DEPRECATED == $errno || E_USER_DEPRECATED == $errno) {
Please don't use YODA syntax.

2024-04-25 21:09 UTC, GuySartorelli commented
Please also retarget this PR to the `4.5` branch so it can be released as a patch.

2024-04-26 01:26 UTC, oddnoc commented
Will open a new PR

2024-04-26 01:26 UTC, closed without merging